### ISSUE TITLE
Stories pages do not display global navigation links

### ISSUE THREAD

**Issue by nelsonic** [foundersandcoders/foundersandcoders.github.io#21]
The navigation does not show on stories.

Steps to re-perform:
1. Visit: http://foundersandcoders.org/
2. Click on Stories (in the top nav). (takes you to: http://foundersandcoders.org/blog.html )
3. Click on any of the story headlines. e.g: Bes: http://foundersandcoders.org/stories/2014/12/12/besart.html

You will see:
![fc-stories-header-missing-bes](https://cloud.githubusercontent.com/assets/194400/6105627/37e01c84-b051-11e4-91cd-0e1711eec835.png)

**Note**: it the nav links showed up when I re-sized the screen... 
![fc-stories-header-shows-when-re-sized](https://cloud.githubusercontent.com/assets/194400/6105652/71eff6ec-b051-11e4-9f3e-c2710b1c333d.png)
I don't know if this is the *desired* behaviour...

**Comment by harrygfox** [comment]
@nelsonic Thanks for bringing this up, I'm pushing a fix now

**Comment by nelsonic** [comment]
Sweet. thanks for letting me know @harrygfox :+1:
